### ISSUE TITLE
Conda Environment can not be reproduced -> ResolvePackageNotFound

### ISSUE THREAD

**Issue by ucyo** [Climate-Data-Science/Climate-Similarity-Metrics#13]
Hi there,

I can not reproduce the environment using the method described in `README.md` 
```shell
conda env create -f environment.yaml
```

## Error
I get the error message
```
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - mistune==0.8.4=py36he774522_0
  - m2w64-gcc-libs-core==5.3.0=7
  - ....
```
## Tried and failed
I tried
- Create a new environment and update it, as suggested [here](https://github.com/datitran/object_detector_app/issues/41#issuecomment-555239417)
- Change config of conda, as suggested [here](https://github.com/datitran/object_detector_app/issues/41#issuecomment-588469805)

## Probable cause
This is probably caused by `conda` since another package has the same issue [[#Issue 41 of ODA](https://github.com/datitran/object_detector_app/issues/41)]

## Environment
- Linux Debian Testing @ Kernel 4.19
- conda 4.8.3

**Comment by pierretoussing** [comment]
@ucyo 
This issue occurs when the target platform is different from the source platform. So I think the reason is you use Linux and the environment was exported on Windows. A solution provided [here](https://github.com/conda/conda/issues/7311) is to export the environment using the `--no-builds` option. I will export it again using this option and wait for your feedback if this solves the problem.

**Comment by ucyo** [comment]
Thank you for the update. The new `environment.yml` file works better now. The number of unresolved packages is less now. The current output with commit `c70932b` is:

```
# conda env create -f environment.yaml                                              
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - wincertstore=0.2
  - msys2-conda-epoch=20160418
  - pywin32=227
  - m2w64-gmp=6.1.0
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - pywinpty=0.5.7
  - vc=14.1
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-gcc-libs=5.3.0
  - vs2015_runtime=14.16.27012
  - winpty=0.4.3
  - icc_rt=2019.0.0
```
Can we update/remove these?

**Comment by pierretoussing** [comment]
I created the `environment.yaml` manually and was able to reduce the **number of requirements** from **106 to 9**. This reduces the potential for conflicts and is recommended by conda itself in order to reach full platform independency. On my second system, everything now works fine. 
Please let me know if there are still conflicts or if some packages needed have been left out.

**Comment by pierretoussing** [comment]
Please notice that running the `conda env create -f environment.yaml ` command might not import the pip requirements. I read that running the command in the cmd.exe would solve this problem.

**Comment by ucyo** [comment]
Done. Now it worked. Thank you for fixing this. The command `conda env create -f environment.yaml` was enough to install everything incl. pip requirements.
